import type { TutorialChapterDefinition } from './types'
import {
  validateBuildingAndLevel,
  validateClosedRoomWalls,
  validateClosedSite,
  validateFloorplanView,
  validateIntro,
  validateOpening,
  validateSlab,
  validateSpawn,
  validateWalkthrough,
} from './validators'

export const TUTORIAL_CHAPTERS: TutorialChapterDefinition[] = [
  {
    id: 'intro',
    milestoneKey: 'intro',
    titleKey: 'tutorial.chapters.intro.title',
    bodyKey: 'tutorial.chapters.intro.body',
    recoveryHintKey: 'tutorial.chapters.intro.hint',
    spotlightTarget: null,
    validate: validateIntro,
  },
  {
    id: 'site',
    milestoneKey: 'site',
    titleKey: 'tutorial.chapters.site.title',
    bodyKey: 'tutorial.chapters.site.body',
    recoveryHintKey: 'tutorial.chapters.site.hint',
    spotlightTarget: 'tutorial-site-edit',
    validate: validateClosedSite,
  },
  {
    id: 'building',
    milestoneKey: 'building',
    titleKey: 'tutorial.chapters.building.title',
    bodyKey: 'tutorial.chapters.building.body',
    recoveryHintKey: 'tutorial.chapters.building.hint',
    spotlightTarget: 'tutorial-structure-build',
    validate: validateBuildingAndLevel,
  },
  {
    id: 'walls',
    milestoneKey: 'walls',
    titleKey: 'tutorial.chapters.walls.title',
    bodyKey: 'tutorial.chapters.walls.body',
    recoveryHintKey: 'tutorial.chapters.walls.hint',
    spotlightTarget: 'tutorial-tool-wall',
    validate: validateClosedRoomWalls,
  },
  {
    id: 'slab',
    milestoneKey: 'slab',
    titleKey: 'tutorial.chapters.slab.title',
    bodyKey: 'tutorial.chapters.slab.body',
    recoveryHintKey: 'tutorial.chapters.slab.hint',
    spotlightTarget: 'tutorial-tool-slab',
    validate: validateSlab,
  },
  {
    id: 'opening',
    milestoneKey: 'opening',
    titleKey: 'tutorial.chapters.opening.title',
    bodyKey: 'tutorial.chapters.opening.body',
    recoveryHintKey: 'tutorial.chapters.opening.hint',
    spotlightTarget: 'tutorial-tool-door',
    validate: validateOpening,
  },
  {
    id: 'spawn',
    milestoneKey: 'spawn',
    titleKey: 'tutorial.chapters.spawn.title',
    bodyKey: 'tutorial.chapters.spawn.body',
    recoveryHintKey: 'tutorial.chapters.spawn.hint',
    spotlightTarget: 'tutorial-tool-spawn',
    validate: validateSpawn,
  },
  {
    id: 'walk',
    milestoneKey: 'walk',
    titleKey: 'tutorial.chapters.walk.title',
    bodyKey: 'tutorial.chapters.walk.body',
    recoveryHintKey: 'tutorial.chapters.walk.hint',
    spotlightTarget: 'tutorial-walkthrough',
    validate: validateWalkthrough,
  },
  {
    id: 'floorplan',
    milestoneKey: 'floorplan',
    titleKey: 'tutorial.chapters.floorplan.title',
    bodyKey: 'tutorial.chapters.floorplan.body',
    recoveryHintKey: 'tutorial.chapters.floorplan.hint',
    spotlightTarget: 'tutorial-view-mode',
    validate: validateFloorplanView,
  },
]
